version: '3'

services:
  minio:
    container_name: minio
    image: minio/minio
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" --address ":9000" /data

  ansible-cli-docker:
    container_name: ansible-cli-docker
    platform: linux/x86_64
    image: haxorof/ansible-core:v2.14-alpine
    volumes:
      - ./:/app

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper

  fake-news-classifier:
    image: fake_news_classificator:latest
    container_name: fake-news-classfier
    volumes:
      - ./data:/app/data
      - ./tmp/result:/app/result
    depends_on:
      - kafka

  fake-news-receiver:
    image: fake_news_receiver:latest
    container_name: fake-news-receiver
    volumes:
      - ./data:/app/data
      - ./tmp/result:/app/result
    depends_on:
      - kafka

volumes:
  minio_storage:
