name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest --cov=src

  build_docker_image:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Get tag or commit
      id: tag_or_commit
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
        else
          echo "::set-output name=version::${GITHUB_SHA}"
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/fake_news_classificator:${{ steps.tag_or_commit.outputs.version }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/fake_news_classificator:latest
      
  run_docker_image:
    needs: build_docker_image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Install DVC
        run: pip install dvc dvc-s3 dvc-webhdfs

      - name: Prepare ANSIBLE_PASS
        run: |
          mkdir -p ./ansible
          echo ${{ secrets.ANSIBLE_PASS }} > ./ansible/ansible_pass.txt

      - name: Prepare DVC for remote storage
        run: |
          export DVC_WEBHDFS_ADDRESS=$(docker-compose run ansible-cli-docker ansible-vault view /app/ansible/webhdfs_address.vault --vault-password-file /app/ansible/ansible_pass.txt | tail -n 1)
          dvc remote add --local remote_webhdfs ${DVC_WEBHDFS_ADDRESS}
          rm -rf ./ansible/ansible_pass.txt

      - name: Pull data and model from DVC remote storage
        run: dvc pull -r remote_webhdfs

      - name: Docker pull image
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/fake_news_classificator:latest
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/fake_news_classificator:latest fake_news_classificator:latest 

      - name: Run Docker-Compose service
        run: docker-compose up fake-news-classifier
